import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  content: {
    width: "100%",
    maxWidth: 360,
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    padding: 20,
    gap: 16,
  },
  closeButton: {
    position: "absolute",
    top: 14,
    right: 14,
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: "#F1F5F9",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingRight: 28,
  },
  iconWrap: {
    width: 46,
    height: 46,
    borderRadius: 14,
    backgroundColor: "#F1F5F0",
    alignItems: "center",
    justifyContent: "center",
  },
  headerText: {
    flex: 1,
    gap: 3,
  },
  eyebrowRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  eyebrowTick: {
    width: 3,
    height: 11,
    borderRadius: 2,
    backgroundColor: "#E8B04B",
  },
  eyebrow: {
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 1.5,
    color: "#B8923F",
  },
  name: {
    fontSize: 19,
    fontWeight: "600",
    color: "#1E293B",
    letterSpacing: -0.3,
  },
  location: {
    fontSize: 13,
    fontWeight: "300",
    color: "#64748B",
    lineHeight: 18,
  },
  card: {
    backgroundColor: "#F8FAFC",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    paddingHorizontal: 14,
    paddingVertical: 4,
  },
  row: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 11,
  },
  fieldText: {
    fontSize: 14,
    fontWeight: "400",
    color: "#475569",
    flex: 1,
  },
  divider: {
    height: 1,
    backgroundColor: "#E2E8F0",
  },
  emptyText: {
    fontSize: 13,
    color: "#94A3B8",
    paddingVertical: 11,
  },
  editForm: {
    gap: 16,
    paddingTop: 4,
  },
  editHeader: {
    gap: 3,
    paddingRight: 28,
  },
  editTitle: {
    fontSize: 19,
    fontWeight: "600",
    color: "#1E293B",
    letterSpacing: -0.3,
  },
  editFields: {
    gap: 12,
  },
  fieldGroup: {
    gap: 4,
  },
  label: {
    fontSize: 11,
    fontWeight: "600",
    letterSpacing: 0.5,
    color: "#94A3B8",
    textTransform: "uppercase",
  },
  input: {
    backgroundColor: "#F8FAFC",
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 11,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    fontSize: 14,
    fontWeight: "400",
    color: "#1E293B",
  },
  actions: {
    flexDirection: "row",
    gap: 10,
  },
  cancelButton: {
    flex: 1,
    height: 46,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#E2E8F0",
    backgroundColor: "#FFFFFF",
  },
  cancelText: {
    fontSize: 14,
    fontWeight: "500",
    color: "#0F172A",
  },
  saveDisabled: {
    backgroundColor: "#94A3B8",
  },
  actionButton: {
    flex: 1,
    height: 46,
    borderRadius: 999,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  editButton: {
    backgroundColor: "#0b4c29",
  },
  editText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#FFFFFF",
  },
  deleteButton: {
    borderWidth: 1,
    borderColor: "#FECACA",
    backgroundColor: "#FEF2F2",
  },
  deleteText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#DC2626",
  },
});
